services:
  postgres:
    image: postgres:16
    container_name: essence-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: essence_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./parfum_ecom_Backend
    container_name: essence-backend
    environment:
      DB_NAME: essence_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./e_commerce_parfum_wd
    container_name: essence-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: